#ifndef _NUMERIC_HPP_INCLUDED_SFDPOIH308Y9AHSLFKDJSADNMKB49UHBADKFN948YAJKLFDS49
#define _NUMERIC_HPP_INCLUDED_SFDPOIH308Y9AHSLFKDJSADNMKB49UHBADKFN948YAJKLFDS49

#include <device/matrix/numeric/expm.hpp>
#include <device/matrix/numeric/gemm.hpp>
#include <device/matrix/numeric/norm.hpp>

#endif//_NUMERIC_HPP_INCLUDED_SFDPOIH308Y9AHSLFKDJSADNMKB49UHBADKFN948YAJKLFDS49

