#ifndef _MATH_HPP_INCLUDED_DSPIONASFPOIJ4P9IFAHDLKJASFD94HIALKFDJAFKLJDHASDFIH49
#define _MATH_HPP_INCLUDED_DSPIONASFPOIJ4P9IFAHDLKJASFD94HIALKFDJAFKLJDHASDFIH49

#include <device/math/abs.hpp>
#include <device/math/acosh.hpp>
#include <device/math/acos.hpp>
#include <device/math/asinh.hpp>
#include <device/math/asin.hpp>
#include <device/math/atan2.hpp>
#include <device/math/atanh.hpp>
#include <device/math/atan.hpp>
#include <device/math/cbrt.hpp>
#include <device/math/ceil.hpp>
#include <device/math/copysign.hpp>
#include <device/math/cosh.hpp>
#include <device/math/cos.hpp>
#include <device/math/cospi.hpp>
#include <device/math/e.hpp>
#include <device/math/erfc.hpp>
#include <device/math/erfcinv.hpp>
#include <device/math/erfcx.hpp>
#include <device/math/erf.hpp>
#include <device/math/erfinv.hpp>
#include <device/math/exp10.hpp>
#include <device/math/exp2.hpp>
#include <device/math/exp.hpp>
#include <device/math/expm1.hpp>
#include <device/math/floor.hpp>
#include <device/math/fmod.hpp>
#include <device/math/hypot.hpp>
#include <device/math/ilogb.hpp>
#include <device/math/inverse.hpp>
#include <device/math/j0.hpp>
#include <device/math/j1.hpp>
#include <device/math/jn.hpp>
#include <device/math/ldexp.hpp>
#include <device/math/lgamma.hpp>
#include <device/math/llrint.hpp>
#include <device/math/llround.hpp>
#include <device/math/log10.hpp>
#include <device/math/log1p.hpp>
#include <device/math/log2.hpp>
#include <device/math/logb.hpp>
#include <device/math/log.hpp>
#include <device/math/lrint.hpp>
#include <device/math/nearbyint.hpp>
#include <device/math/normcdf.hpp>
#include <device/math/normcdfinv.hpp>
#include <device/math/pi.hpp>
#include <device/math/pow.hpp>
#include <device/math/rcbrt.hpp>
#include <device/math/remainder.hpp>
#include <device/math/rint.hpp>
#include <device/math/round.hpp>
#include <device/math/rsqrt.hpp>
#include <device/math/scalbln.hpp>
#include <device/math/scalbn.hpp>
#include <device/math/sgn.hpp>
#include <device/math/sinh.hpp>
#include <device/math/sin.hpp>
#include <device/math/sinpi.hpp>
#include <device/math/sqrt.hpp>
#include <device/math/tanh.hpp>
#include <device/math/tan.hpp>
#include <device/math/tgamma.hpp>
#include <device/math/trunc.hpp>
#include <device/math/y0.hpp>
#include <device/math/y1.hpp>
#include <device/math/yn.hpp>

#endif//_MATH_HPP_INCLUDED_DSPIONASFPOIJ4P9IFAHDLKJASFD94HIALKFDJAFKLJDHASDFIH49

