#ifndef EGIDQNJGGDBRMGPIMPSETOBLFSEYSDJMXITRXGMYOFXRXBWCUHKOKSSQIYIXOCSGOVTUHOKKU
#define EGIDQNJGGDBRMGPIMPSETOBLFSEYSDJMXITRXGMYOFXRXBWCUHKOKSSQIYIXOCSGOVTUHOKKU

#include <numeric/matrix/numeric/function/transpose.hpp>
#include <numeric/matrix/numeric/function/norm.hpp>

namespace numeric
{

}//namespace numeric

#endif//EGIDQNJGGDBRMGPIMPSETOBLFSEYSDJMXITRXGMYOFXRXBWCUHKOKSSQIYIXOCSGOVTUHOKKU

